Fix stopmonitorprinter link text in API doc
tr3v3r/react-native-esc-pos-printer pull request #15
Opened 2021-08-02 17:18 UTC by user512

2021-08-03 07:36 UTC, tr3v3r requested changes

2021-08-03 07:36 UTC, tr3v3r commented on docs/API.md
> +6. [stopmonitorprinter](#stopmonitorprinter)
Should be in camel case. 
```
stopMonitorPrinter
```

2021-08-03 19:32 UTC, user512 commented on docs/API.md
> +6. [stopmonitorprinter](#stopmonitorprinter)
Thanks!
```suggestion
6. [stopMonitorPrinter](#stopmonitorprinter)
```

2021-08-04 08:57 UTC, tr3v3r approved these changes

2021-08-04 08:57 UTC, merged