feat: adding addPulse functionality
tr3v3r/react-native-esc-pos-printer pull request #35
Opened 2021-11-14 11:59 UTC by MinaZakaria

Adding addPulse functionality to open the cash drawer

related to the issue: https://github.com/tr3v3r/react-native-esc-pos-printer/issues/17 

Tested on IOS Simulator
Tested on Android Device

2021-11-14 12:49 UTC, tr3v3r commented
@MinaZakaria hi! Thanks!
Looks fine. One moment, could you please update docs as well?

2021-11-14 12:51 UTC, tr3v3r requested changes

2021-11-14 12:51 UTC, tr3v3r commented on android/src/main/java/com/reactnativeescposprinter/EscPosPrinterModule.java
> +      constants.put("EPOS2_PARAM_DEFAULT", Printer.PARAM_DEFAULT);
Do we need this constant?

2021-11-14 13:45 UTC, MinaZakaria commented on android/src/main/java/com/reactnativeescposprinter/EscPosPrinterModule.java
> +      constants.put("EPOS2_PARAM_DEFAULT", Printer.PARAM_DEFAULT);
no we don't .. I removed it

2021-11-16 09:22 UTC, MinaZakaria commented
Could you please merge the feature if there is no any further comments ?

2021-11-16 11:00 UTC, tr3v3r commented
@MinaZakaria hi! do you have time to resolve the latest comment? (About pin parameter)

2021-11-16 12:07 UTC, MinaZakaria commented
> @MinaZakaria hi! do you have time to resolve the latest comment? (About pin parameter)

I think you forget to submit the latest comment .. I cannot find it

2021-11-16 12:26 UTC, tr3v3r commented
@MinaZakaria sorry for that( just submitted. After update I’ll immediately merge and prepare new release

2021-11-17 12:53 UTC, MinaZakaria commented
@tr3v3r  The latest comment applied but I didn't test as I cannot access the drawer right now. You can review and test if you want. Or I'll test it next Sunday.

2021-11-17 14:46 UTC, tr3v3r commented
@MinaZakaria actually your code will not work because you need use numbers exporter from native. ( see image printing method as example ). 

Ok. If I have a capacity I’ll update it by my own tomorrow

2021-11-18 09:41 UTC, merged

2021-11-21 08:02 UTC, MinaZakaria commented
Thank you for merging .. could you please add a new release or should I use the main branch?

2021-11-21 12:47 UTC, tr3v3r commented
@MinaZakaria hi. Release is planned for tomorrow

2021-11-22 08:36 UTC, tr3v3r commented
@MinaZakaria  just released version 1.5.0. Please check if everything works as expected

2021-11-22 11:00 UTC, MinaZakaria commented
Hello @tr3v3r 
Unfortunately. it's not working.
the assertion failed with the error
```
[Error: Error: EPOS2_DRAWER_2PIN is not valide property value for addPulse]
```
same error if used `EPOS2_DRAWER_5PIN`

when I print `EscPosPrinter.getConstants();` It doesn't have the `EPOS2_DRAWER_2PIN` key !
I don't know what is the cause of the problem.

2021-11-22 11:12 UTC, tr3v3r commented
@MinaZakaria have you run pod install after update ?

2021-11-22 14:55 UTC, tr3v3r commented
@MinaZakaria Just tested on iOS on version 1.5.0 - no errors. 
Could you please try to clean and re-install the latest version and confirm one more time?

2021-11-24 08:42 UTC, MinaZakaria commented
Just tested and everything is working like a Charm. Thank you 👍 💘