Only the first printer is reported after discovery
tr3v3r/react-native-esc-pos-printer pull request #9
Opened 2021-06-01 11:38 UTC by JesperBadstue

I noticed that when discovering printers the `DiscoveryListener` was first called with one printer, and shortly thereafter with two printers etc by the Eposon lib.
The problem is then that as soon at we get a printer in the listener we send the event `onDiscoveryDone` and the react part of the lib stops listening to any more events. This means that the second discovered printer was never reported.
I have added a `mOnDiscoveryReporter ` that delays the emitting of `onDiscoveryDone` for 3 seconds to allow us to discover more than one printer. The 3 seconds is more or less arbitrarily chosen and I guess it could be made configurable if needed.

2021-06-01 21:13 UTC, tr3v3r commented
Hi @JesperBadstue ! Is this issue also reproduced on iOS? 
Since I don't have several devices, could please try to search printers by running an example app from this repo?

Actually, I suppose it's not an ideal solution for this issue, since are already waiting for 5 seconds after running Discovery.start(). So possibly better to shift sending an event into performing the discovery method?

Please look through my notes in the code

2021-06-01 21:21 UTC, tr3v3r requested changes

2021-06-01 21:21 UTC, tr3v3r commented on android/src/main/java/com/reactnativeescposprinter/EscPosPrinterDiscoveryModule.java
> +            WritableArray stringArray = Arguments.createArray();
let's extract this forming and sending data into separate method like: 
```
public void sendDiscoveredDataToJS() {

  WritableArray stringArray = Arguments.createArray();
  for (int counter = 0; counter < mPrinterList.size(); counter++) {
      final DeviceInfo info = mPrinterList.get(counter);
      WritableMap printerData = Arguments.createMap();
      
     ........
     
     sendEvent(reactContext, "onDiscoveryDone", stringArray);
     }
```

And try to send in right after discovery done (after 5 sec) here:

```
  private void performDiscovery(MyCallbackInterface callback) {  
    final Handler handler = new Handler();
    final Runnable r = new Runnable() { 
         public void run() {   
           if(mPrinterList.size() > 0) {
                sendDiscoveredDataToJS() // will be invoked after 5 sec with acc. results
           }
           stopDiscovery();       
           callback.onDone("Search completed"); 
           }   
        };
      handler.postDelayed(r, 5000);
     }
```

2021-06-02 07:16 UTC, JesperBadstue commented
> Hi @JesperBadstue ! Is this issue also reproduced on iOS?
> Since I don't have several devices, could please try to search printers by running an example app from this repo?
> 
> Actually, I suppose it's not an ideal solution for this issue, since we are already waiting for 5 seconds after running Discovery.start(). So possibly better to shift sending an event into performDiscovery method?
> 
> Please look through my notes in the code

Hi @tr3v3r
Unfortunately I dont have any iOS devices so I dont know if it has the same problems:(

You are right that we should just the 5 sec delay already in the `performDiscovery` I'll update the PR.

2021-06-02 08:14 UTC, tr3v3r approved these changes

2021-06-02 08:14 UTC, merged

2021-06-02 08:15 UTC, tr3v3r commented
@JesperBadstue merged. I'll try to prepare a new release today. Thanks for your help!